version: "3"
services:
  rabbitmq:
    image: localhost:5000/rabbitmq-nayco
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672 # Web management console. Default account guest:guest
      - 1883:1883 # MQTT Port

  # RabbitMQ to ClickHouse
  grebe:
    image: tac0x2a/grebe:v1.0.3
    hostname: grebe
    restart: always
    environment:
      - MQ_QNAME=nayco # Queue name to subscribe on RabbitMQ
      - MQ_HOST=rabbitmq # RabbitMQ host
      - DB_HOST=clickhouse # Clickhouse host
    volumes:
      - nayco-grebe-logs:/logs
      - nayco-grebe-schemas:/schemas

  # Column-oriented DWH. db=default, user=default, pass=default
  clickhouse:
    image: yandex/clickhouse-server:20.5.2.7
    hostname: clickhouse
    restart: always
    ports:
      - 8123:8123 # HTTP client port
    volumes:
      - nayco-clickhouse:/var/lib/clickhouse

  # Portainer - Monitoring containers
  portainer: # admin - tryportainer
    image: portainer/portainer:1.24.0
    hostname: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nayco-portainer-data:/data

  # Metabase visualize data on ClickHouse.
  metabase:
    image: localhost:5000/metabase-nayco
    hostname: metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - nayco-metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db

  # Tabix - Clickhouse web based client
  tabix:
    image: spoonest/clickhouse-tabix-web-client:stable
    hostname: tabix
    restart: always
    ports:
      - 8080:80
    environment:
      CH_HOST: clickhouse:8123

  # Node-RED
  node-red:
    image: nodered/node-red-docker:v10
    hostname: nodered
    restart: always
    ports:
      - 1880:1880
    volumes:
      - nayco-nodered-data:/data
    user: root:root

volumes:
  nayco-grebe-logs:     {driver: local}
  nayco-grebe-schemas:  {driver: local}
  nayco-clickhouse:     {driver: local}
  nayco-portainer-data: {driver: local}
  nayco-metabase-data:  {driver: local}
  nayco-nodered-data:   {driver: local}