version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8.2-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672" # Web management console. Default account guest:guest
      - "1883:1883" # MQTT Port
    volumes:
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

  # RabbitMQ to ClickHouse
  grebe:
    image: tac0x2a/grebe:v0.3
    hostname: grebe
    restart: always
    environment:
      - MQ_QNAME=biwako # Queue name to subscribe on RabbitMQ
      - MQ_HOST=rabbitmq # RabbitMQ host
      - DB_HOST=clickhouse # Clickhouse host
    volumes:
      - ./volume/grebe/logs:/logs
      - ./volume/grebe/schemas:/schemas

  # Column-oriented DWH. db=default, user=default, pass=default
  clickhouse:
    image: yandex/clickhouse-server:20.1.6.3
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123" # HTTP client port
    volumes:
      - ./volume/clickhouse:/var/lib/clickhouse

  # Portainer - Monitoring containers
  portainer: # admin - tryportainer
    image: portainer/portainer:1.23.1
    hostname: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume/portainer/data:/data
