# For development
version: "3"
services:
  web_flask:
    build:
      context: backend
      args:
        project_directory: "/projects/"
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/projects"
      - "./frontend:/frontend"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
      DB_HOST: "192.168.11.200"
      DB_PORT: 9000
    command: "flask run --host 0.0.0.0 --port 5000"

  web_vue:
    container_name: frontend
    build:
      context: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      API_HOST: web_flask
    ports:
      - '8081:8080'